apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-master-config1
  labels:
    app: elasticsearch
    role: master
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    node.name:    ${NODE_NAME}
    discovery.seed_hosts: ${NODE_LIST}
    cluster.initial_master_nodes: ${MASTER_NODES}
    network.host: 0.0.0.0
    node:
      master: true
      data: false
      ingest: false
      #xpack.security.enabled: true
      #xpack.monitoring.collection.enabled: true
      
apiVersion: v1
kind: Pod
metadata:
  name: elastictrail
  labels:
    app: elastictrail
spec:
  containers:
    - name: elastictrail
      image: elasticsearch
      env:
       - name: CLUSTER_NAME
         value: elasticsearch1
       - name: NODE_NAME
         value: elasticsearch-master1
       - name: NODE_LIST
         value: elasticsearch-master,elasticsearch-data,elasticsearch-client
       - name: MASTER_NODES
         value: elasticsearch-master1
       - name: "ES_JAVA_OPTS"
         value: "-Xms256m -Xmx256m"
       ports:
          - containerPort: 9400
